# Site settings
title: najx
description: >- # site description
  Notes and practical guides on cloud computing, DevOps, platform engineering,
  networking and AI. A personal technology blog by N.A.
lang: en-US # default lang
timezone: Europe/Zurich # set your timezone
image: /assets/img/najx.svg
repo: https://github.com/najx/najx.github.io # https://github.com/piharpi/jekyll-klise # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: N.A. # author name
  bio: >- # tell to the world
    There is no place like 127.0.0.1
  username: # general username
  github: # github username
  twitter: # twitter username
  facebook: # facebook username
  email: # email adress
  avatar:
    - /assets/home/main.svg

# URL settings
url: "https://najx.dev" #
baseurl:
permalink: /:title/
google_analytics: G-TESDGR3TCF
fb_appid: # leave it blank if not wish

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 6

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - scripts
  - docs
  - vendor
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
