baseURL: # if your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
title: # Top left corner icon
paginate: 5
theme: charlolamode

menu:
    main:
        #- name: Project
        #  url: /projects/
        #  weight: 15
        - name: Articles
          url: /articles/
          weight: 15
        - name: Contact
          url: /contact/
          weight: 30
        - name: About
          url: /about/
          weight: 20

params:
    author: naj(x)
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true

    profileMode:
        # Disable to populate home page with 'mainSections' content
        enabled: true
        #title: naj(x) {AI}
        #description: |
        #  💡🤖🔍📚💻📊
        imageUrl: "/images/n.png"
        imageTitle: my image
        imageWidth: 400
        imageHeight: 400
        #buttons:
        #    - name: About
        #      url: http://localhost:1313/about/
    mainSections:
      - articles

    socialIcons:
        - name: github
          url: "https://github.com/najx"
        - name: linkedin
          url: "https://www.linkedin.com/in/abdx/"

    # change favicon in images folder (icon for web tab)
    assets:
          favicon: "/images/favicon.ico"
          favicon16x16: "/images/favicon-16x16.png"
          favicon32x32: "/images/favicon-32x32.png"
          apple_touch_icon: "/images/apple-touch-icon.png"
          safari_pinned_tab: "/images/apple-touch-icon.png"

enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
